---
title: "Assignment 1"
---

# Assignment 1

My first assignment has two parts.

## (a)
```{r}
# I chose to summarize the video where Baykal Hafızoğlu is the guest. 

## Summary
#

## Question 1

```


## (b)
```{r}
#getting the dataset
install.packages("dslabs")
library(dslabs)
data("polls_us_election_2016")
#first 10 rows
ten_rows <- head(polls_us_election_2016, 10)
ten_rows
#total number of na's
total_na <- sum(is.na(polls_us_election_2016))
total_na
#replacing na values
birth_year <- 2002
name <- "bihter"
#dataset to modify
modified_data_set <- polls_us_election_2016

#replace NA values in columns 
for (i in seq_along(modified_data_set)) {
  if (is.numeric(modified_data_set[[i]])) {
    modified_data_set[[i]][is.na(modified_data_set[[i]])] <- birth_year
  } else if (is.character(modified_data_set[[i]])) {
    modified_data_set[[i]][is.na(modified_data_set[[i]])] <- name
  }
}


#display the first 10 rows and number of na's
modified_ten_rows <- head(modified_data_set, 10)
modified_ten_rows
total_na <- sum(is.na(modified_data_set))
total_na
```


